name: 'Generate Html from git diff'
description: 'Generate Html from git diff'
inputs:
  git-diff:  # id of input
    description: 'Git diff'
    required: true
    default: 'diff'
outputs:
  diff2html: # id of output
    description: 'diff2html'
runs:
  using: 'node16'
  main: 'index.js'