name: 'Generate Html from git diff'
description: 'Generate Html from git diff'
inputs:
  config-file:  # id of input
    description: 'Configuration file name to ignore files in comparison'
    required: true
    default: 'config.deploy.yml'
  output-file-name:
    description: 'Resulting html file from git diff'
    required: true
    default: 'git-diff.html'
runs:
  using: 'node16'
  main: 'index.js'