development:
  # password: PASSWORD
  # theme_id: "THEME_ID"
  # store: STORE_NAME.myshopify.com
  ignore_files:
  - config/settings_data.json
  - locales/en.default.json
  - templates/product.json.liquid
  - templates/404.json
  - templates/article.liquid
  - templates/blog.liquid
  - templates/cart.json
  - templates/collection.json
  - templates/gift_card.json
  - templates/index.json
  - templates/list-collections.json
  - templates/page.home.json
  - templates/page.json
  - templates/password.json
  - templates/product.json
  - templates/search.json
  - templates/page.about-us.json
  - templates/customers/account.json
  - templates/customers/addresses.json
  - templates/customers/order.json
  - templates/*.json
  - layout/theme.shogun.landing.liquid
  - sections/shogun-above.liquid
  - sections/shogun-below.liquid
  - sections/shogun-helper.liquid
  - snippets/shogun-head.liquid
  - snippets/shogun-products.liquid
  - templates/page.shogun.default.liquid
  - templates/page.shogun.landing.liquid
  - templates/product.shogun.custom.liquid
  - templates/index.liquid
  - sections/footer.liquid
  - templates/page.contact.liquid
  - templates/404.liquid
  - templates/search.liquid